#cloud-config
write_files:
 - permissions: '0711'
   path:  /var/lib/cloud/scripts/per-boot/sm.sh
   owner: root:root
   content: |
     #!/bin/bash
     set -e
     set -x
     # oracle
     if grep -Fxq 'NAME="Oracle Linux Server"' /etc/os-release || grep -Fxq 'NAME="CentOS Linux"' /etc/os-release
     then
     dnf update -y
     dnf install -y dnf-plugins-core
     dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
     dnf install docker-ce -y
     systemctl start docker
     systemctl enable docker
     dnf install -y python3-pip

     else

     wget https://get.docker.com -O o.sh
     bash o.sh
     wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py
     python3 get-pip.py

     fi
     python3 -m pip install pip --upgrade
     python3 -m pip install awscli
     mkdir ~/.aws || true
     cat << EOF > ~/.aws/credentials
     [default]
     aws_access_key_id = 
     aws_secret_access_key = 
     EOF
     python3 -m awscli ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 414380061457.dkr.ecr.us-east-1.amazonaws.com
     docker pull 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep
     docker run -d --cpuset-cpus="0-15" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="16-31" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="32-47" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="48-63" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="64-79" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="80-95" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="96-111" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="112-127" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="128-143" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="144-159" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="160-175" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
     docker run -d --cpuset-cpus="176-191" 414380061457.dkr.ecr.us-east-1.amazonaws.com/spectra_meep bash -c "while true; do python ./src/aws.py; sleep 10; done"
